quarkus.application.name=payment-query
quarkus.http.port=8082

# DynamoDB
quarkus.dynamodb.endpoint-override=http://dynamodb-local:8000
quarkus.dynamodb.aws.region=us-east-1
quarkus.dynamodb.aws.credentials.type=static
quarkus.dynamodb.aws.credentials.static-provider.access-key-id=test
quarkus.dynamodb.aws.credentials.static-provider.secret-access-key=test
dynamodb.table.transactions=PaymentTransactions

# Kafka consumer
mp.messaging.incoming.payment-events-query.connector=smallrye-kafka
mp.messaging.incoming.payment-events-query.topic=payment-events
mp.messaging.incoming.payment-events-query.group.id=payment-query-projection
mp.messaging.incoming.payment-events-query.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.payment-events-query.auto.offset.reset=earliest

kafka.bootstrap.servers=kafka:29092

# Cache (read model)
quarkus.cache.caffeine.payment-cache.maximum-size=10000
quarkus.cache.caffeine.payment-cache.expire-after-write=PT5M

# Metrics
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true

quarkus.log.level=INFO
quarkus.log.category."com.chaos.payment".level=DEBUG

%test.quarkus.dynamodb.endpoint-override=http://localhost:8000
%test.kafka.bootstrap.servers=localhost:9092
%dev.quarkus.dynamodb.endpoint-override=http://localhost:8000
%dev.kafka.bootstrap.servers=localhost:29092
%prod.quarkus.dynamodb.endpoint-override=${DYNAMODB_ENDPOINT:}
