quarkus.application.name=fraud-detection
quarkus.http.port=8083

# DynamoDB
quarkus.dynamodb.endpoint-override=http://dynamodb-local:8000
quarkus.dynamodb.aws.region=us-east-1
quarkus.dynamodb.aws.credentials.type=static
quarkus.dynamodb.aws.credentials.static-provider.access-key-id=test
quarkus.dynamodb.aws.credentials.static-provider.secret-access-key=test
dynamodb.table.fraud-history=FraudHistory
dynamodb.table.blacklist=FraudBlacklist

# Kafka
mp.messaging.incoming.payment-events-fraud.connector=smallrye-kafka
mp.messaging.incoming.payment-events-fraud.topic=payment-events
mp.messaging.incoming.payment-events-fraud.group.id=fraud-detection
mp.messaging.incoming.payment-events-fraud.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.payment-events-fraud.auto.offset.reset=earliest

mp.messaging.outgoing.fraud-alerts.connector=smallrye-kafka
mp.messaging.outgoing.fraud-alerts.topic=fraud-alerts
mp.messaging.outgoing.fraud-alerts.value.serializer=org.apache.kafka.common.serialization.StringSerializer

kafka.bootstrap.servers=kafka:29092

# Fraud rules config
fraud.risk.block-threshold=80
fraud.risk.review-threshold=40
fraud.amount.high-risk=500000
fraud.velocity.max-per-minute=5

# Metrics
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true

quarkus.log.level=INFO
quarkus.log.category."com.chaos.payment".level=DEBUG

%test.quarkus.dynamodb.endpoint-override=http://localhost:8000
%test.kafka.bootstrap.servers=localhost:9092
%dev.quarkus.dynamodb.endpoint-override=http://localhost:8000
%dev.kafka.bootstrap.servers=localhost:29092
%prod.quarkus.dynamodb.endpoint-override=${DYNAMODB_ENDPOINT:}
